package fr.inria.contraintes.biocham.customComponents;

import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.ModernBalloonStyle;

import java.awt.Color;

import javax.swing.JLabel;



/**
 * Class that creates the red information label on the toolbar that popups when error/warning is generated by Biocham.
 * 
 * @author Dragana Jovanovska  
 */ 
public class BiochamInfoLabel extends JLabel{
	CustomBalloonTip tp;
	String texto="";
	static final Color color1=new Color(255,0,0);//blue, 
	static final Color color2=new Color(230,230,230);//grey
	static final Color color3=new Color(204,204,204);//darker grey
	
	public void setText(String text) {
		
		if(tp!=null){
			tp.setText(text);	
		}
		
	}
	public BiochamInfoLabel(String ttt){
		super(ttt);
				
		//addMouseListener(this);
		
		
		if(ttt!=null){
			ModernBalloonStyle modern=new ModernBalloonStyle(4,4,color1,color2,color3);
			modern.setBorderThickness(3);
			modern.enableAntiAliasing(true);
			tp=new CustomBalloonTip(this,ttt,modern,BalloonTip.Orientation.LEFT_ABOVE,BalloonTip.AttachLocation.SOUTHEAST,20,10,true);
			tp.setText(ttt);
			//tp.enableClickToClose(true);
			tp.enableClickToHide(true);
			tp.setVisible(false);
			/*if(ttt.equals("molecule")){
				setForeground(Utils.moleculeOperatorColor);
			}else if(ttt.equals("parameter")){
				setForeground(Utils.parameterOperatorColor);
			}else{
				setForeground(Color.BLUE);
			}	*/
		}
		
		
			
	}
	public void setToolTipTexto(String s){
		texto=s;
	}
	public void setBalloonToolTipVisible(boolean b){
		if(b){
			tp.setVisible(true);
			
		}else{
			tp.setVisible(false);
		}
	}

	/*public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void mouseEntered(MouseEvent e) {
		if(e.getSource() instanceof CustomToolTipLabel && tp!=null){
			BiochamInfoLabel b=(BiochamInfoLabel)e.getSource();
			b.setBalloonToolTipVisible(true);			
		}
	}
	public void mouseExited(MouseEvent e) {		
		if(e.getSource() instanceof BiochamInfoLabel && tp!=null){
			BiochamInfoLabel b=(BiochamInfoLabel)e.getSource();
			b.setBalloonToolTipVisible(false);
		}
	}

	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void mouseReleased(MouseEvent e) {
		if(e.getSource() instanceof BiochamInfoLabel && tp!=null){
			BiochamInfoLabel b=(BiochamInfoLabel)e.getSource();
			b.setBalloonToolTipVisible(false);
		}
		
	}
	*/

}
