package fr.inria.contraintes.biocham.customComponents;

import javax.swing.JComponent;

import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.BalloonTipStyle;


/**
 * Class thats creates a custom Balloon tip label for visualizing the red information label on the toolbar that popups when error/warning is generated by Biocham (BiochamInfoLabel).
 * 
 * @author Dragana Jovanovska  
 */ 
public class CustomBalloonTip extends BalloonTip{

	public CustomBalloonTip(JComponent arg0, String arg1, BalloonTipStyle arg2, Orientation arg3, AttachLocation arg4, int arg5, int arg6, boolean arg7) {
		super(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
		// TODO Auto-generated constructor stub
	}

	@Override
	public void closeBalloon() {
		setVisible(false);
		/*attachedComponent.removeComponentListener(attachedComponentListener);
		if (topLevelContainer != null) {
			topLevelContainer.remove(this);
			topLevelContainer.removeComponentListener(attachedComponentListener);
		}
		removeMouseListener(clickListener);*/
	}

}
